---
name: CI

on:
    push:
        branches:
            - add_CI_by_github_actions#60
    workflow_dispatch:

jobs:
    unit-test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: [3.x]
        steps:
            - uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: display test env
              run: python3 -c "import sys; print(sys.platform)" && python -V

            - name: install dependencies
              run: python3 -m pip install -r requirements.txt

            - name: install the package
              run: python3 -m pip install .

            - name: unit test
              run: pytest
